In [1]:
import numpy as np

In [78]:
f = open("input.txt","r")
n = f.readline()
print(n)
n = int(n)
A = np.array(np.zeros((n,n+1)))
for i in range(n):
    st = f.readline()
    string = st.split()
    for j in range(n+1):
        A[i][j] = int(string[j])
        
L,U = crout(A,n)
print(A)
# print(L)
# print(U)
out = "L = "
x=np.array2string(L,formatter={'float_kind': lambda L: "%.2f" % L})
y=np.array2string(U,formatter={'float_kind': lambda U: "%.2f" % U})
# print(str(6))
# print(x)
# for i in range(n):
#     for j in range(n):
# #         x=float(L[i][j])
# #         ab=str(x)
# #         print(type(x))
#         out = out + L[i][j] + '\t'
#     out += '\n\t'
wr = open("output.txt","w")
out = out +"\n"+x +"\n" + "U ="+"\n"+ y
wr.write(out)
print(np.dot(L,U))

10

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.  1.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.  2.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.  3.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.  1.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.  2.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.  3.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.  1.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.  2.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.  3.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.  1.]]
[[ 1.  2.  3. nan nan nan nan nan nan nan]
 [11. 12. 13. nan nan nan nan nan nan nan]
 [21. 22. 23. nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]


C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:29: RuntimeWarning: invalid value encountered in double_scalars


In [76]:
def crout(A,n):
    L = np.array(np.zeros((n,n)))
    U = np.array(np.zeros((n,n)))
    for i in range(n):
        U[i][i]=1
    L[:,0] = A[:,0]
    for j in range(n):
        if j >=1:
            U[0][j]=A[0][j]/L[0][0]
    
    for j in range(n-1):
        if j>=1:
            for i in range(n):
                if i >=j:
                    L[i][j] = A[i][j]
                    sum = 0
                    for k in range(j):
                        sum += L[i][k] * U[k][j] 
#                     print(i,j,sum)
                    L[i][j] -= sum
            for k in range(n):
                if k>j:
                    U[j][k] = A[j][k]
                    sum=0
                    for i in range(j):
                        sum += L[j][i]*U[i][k]
#                     print(j,k,sum)
                    U[j][k] -= sum
                    U[j][k] /= L[j][j]
                    
    L[n-1][n-1] = A[n-1][n-1]
    sum=0
    for k in range(n-1):
        sum += L[n-1][k]*U[k][n-1]
    L[n-1][n-1] -= sum
#     print(L,U,A)
    return L,U