In [4]:
import numpy as np
import re

In [60]:
string_list = list()
for i in range (3):
    var = input()
    string_list.append(var)
mat = np.array(np.zeros((3,4)))

x1 - x2 + x3 = 2
2x1 + 3x2 - x3 = -2
-x1 - x2 - 2x3 = 1


In [61]:
mat,all_cap = is_all_cap(string_list, len(string_list) , mat)
if all_cap:
    print(mat)
else:
    mat,all_small = is_all_small(string_list, len(string_list) , mat)
    if all_small:
        print(mat)
    else:
        print('Input Error')

[[ 1. -1.  1.  2.]
 [ 2.  3. -1. -2.]
 [-1. -1. -2.  1.]]


In [55]:
def is_all_cap(string_list, m, mat):
    p_flag = False
    m_flag = False
    e_flag = False
#     o_flag = False
    s_flag = False
    for i in range(m):
        string = string_list[i].split()
#         print(string)
        s_flag = True
        k=0
#         val = 1
        for j in string:
#             print(j)
            if s_flag or e_flag:
                if j[0]=='-':
                    m_flag = True
                    j=j.replace('-','')
#                     print(j)
                else:
                    p_flag = True
#                 if 64<j[0] and j[0]<91:
#                     mat[i][k++] 
#             if len(j) == 1: and !e_flag and !p_flag and !m_flag:
            if j == "+":
                p_flag = True
            elif j == "-":
                m_flag = True
            elif j == "=":
                e_flag = True
            else:
                if not e_flag:
                    x = re.search("[0-9]*[A-Z]$",j)
#                     print(x)
                    if(x):
                        val = re.findall("[0-9]+",j)
#                         print(val)
                        if val:
                            if p_flag:
                                mat[i][k] = int(val[0])
                            elif m_flag:
                                mat[i][k] = -1*int(val[0])
                            k +=1
                        else:
                            if m_flag:
                                mat[i][k] = -1
                            elif p_flag:
                                mat[i][k] = 1
                            k +=1
                    else:
                        return mat,False
                else:
                    x = re.search("[0-9]*$",j)
#                     print(x)
                    if(x):
                        val = re.findall("[0-9]+",j)
#                         print(val)
                        if val:
                            if p_flag:
                                mat[i][k] = int(val[0])
                            elif m_flag:
                                mat[i][k] = -1*int(val[0])
                            k +=1
                        else:
                            if m_flag:
                                mat[i][k] = -1
                            elif p_flag:
                                mat[i][k] = 1
                            k +=1
                    else:
                        return mat,False
                p_flag = False
                m_flag = False
                e_flag = False
#                 o_flag = False
#                 s_flag = False
            s_flag=False
    return mat,True
                        
            

In [58]:
def is_all_small(string_list, m, mat):
    p_flag = False
    m_flag = False
    e_flag = False
#     o_flag = False
    s_flag = False
    for i in range(m):
        string = string_list[i].split()
#         print(string)
        s_flag = True
        k=0
#         val = 1
        for j in string:
#             print(j)
            if s_flag or e_flag:
                if j[0]=='-':
                    m_flag = True
                    j=j.replace('-','')
#                     print(j)
                else:
                    p_flag = True
#                 if 64<j[0] and j[0]<91:
#                     mat[i][k++] 
#             if len(j) == 1: and !e_flag and !p_flag and !m_flag:
            if j == "+":
                p_flag = True
            elif j == "-":
                m_flag = True
            elif j == "=":
                e_flag = True
            else:
                if not e_flag:
                    x = re.search("[0-9]*[a-z][1-9]$",j)
#                     print(x)
                    if(x):
                        val = re.findall("^[0-9]+",j)
#                         print(val)
                        if val:
                            if p_flag:
                                mat[i][k] = int(val[0])
                            elif m_flag:
                                mat[i][k] = -1*int(val[0])
                            k +=1
                        else:
                            if m_flag:
                                mat[i][k] = -1
                            elif p_flag:
                                mat[i][k] = 1
                            k +=1
                    else:
                        return mat,False
                else:
                    x = re.search("[0-9]*$",j)
#                     print(x)
                    if(x):
                        val = re.findall("[0-9]+",j)
#                         print(val)
                        if val:
                            if p_flag:
                                mat[i][k] = int(val[0])
                            elif m_flag:
                                mat[i][k] = -1*int(val[0])
                            k +=1
                        else:
                            if m_flag:
                                mat[i][k] = -1
                            elif p_flag:
                                mat[i][k] = 1
                            k +=1
                    else:
                        return mat,False
                p_flag = False
                m_flag = False
                e_flag = False
#                 o_flag = False
#                 s_flag = False
            s_flag=False
    return mat,True