In [1]:
import numpy as np

In [2]:
f = open("input.txt","r")
n = f.readline()
print(n)
n = int(n)
A = np.array(np.zeros((n,n+1)))
for i in range(n):
    st = f.readline()
    string = st.split()
    for j in range(n+1):
        A[i][j] = int(string[j])

5



In [3]:
def L_Calculation(A,L,U,i,j):
    sum=0
    for k in range(j):
        sum += L[i][k]*U[k][j]
    return A[i][j] - sum

In [4]:
def U_Calculation(A,L,U,i,j):
    sum=0
    for k in range(i):
        sum += L[i][k]*U[k][j]
    return A[i][j] - sum

In [5]:
def dolittle(A,L,U,n):
    for j in range(n):
        for i in range(n):
            if i>j:
                L[i][j] = L_Calculation(A,L,U,i,j)/U[j][j]
            else:
                U[i][j] = U_Calculation(A,L,U,i,j)
    return L,U

In [8]:
L = np.array(np.zeros((n,n)))
U = np.array(np.zeros((n,n)))
# for i in range(n):
#     L[i][i]=1
# L,U = dolittle(A,L,U,n)
for i in range(n):
    U[i][i]=1
L,U = crout(A,L,U,n)
print(A,L,U)
print(np.dot(U,L))

    

[[ 1. -1.  3.  2. -2.  4.]
 [-3.  2.  1.  4. -1.  8.]
 [ 3. -1.  2.  3.  4. -2.]
 [ 2.  1. -3.  2. -2.  4.]
 [ 2.  1.  2. -4. -5.  2.]] [[   1.            0.            0.            0.            0.        ]
 [  -3.           -1.            0.            0.            0.        ]
 [   3.            2.           13.            0.            0.        ]
 [   2.            3.           21.            0.53846154    0.        ]
 [   2.            3.           26.          -12.         -293.42857143]] [[  1.          -1.           3.           2.          -2.        ]
 [  0.           1.         -10.         -10.           7.        ]
 [  0.           0.           1.           1.30769231  -0.30769231]
 [  0.           0.           0.           1.         -23.28571429]
 [  0.           0.           0.           0.           1.        ]]
[[ 1.30000000e+01  7.00000000e+00  2.90000000e+01  2.50769231e+01
   5.86857143e+02]
 [-3.90000000e+01 -3.00000000e+01 -1.58000000e+02 -8.93846154e+01
  -2.0

In [6]:
def crout(A,L,U,n):
    for j in range(n):
        for i in range(n):
            if i>=j:
                L[i][j] = L_Calculation(A,L,U,i,j)
            else:
                U[i][j] = U_Calculation(A,L,U,i,j)/L[i][i]
    return L,U